import type { Metadata } from "next"
import { Toaster } from "@/shared/components/ui/sonner"
import { ThemeProvider } from "@/shared/components/theme-provider"
import { ThemeToggle } from "@/shared/components/theme-toggle"
import "./app.css"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="relative">
						{children}
						<div className="absolute bottom-4 right-4">
							<ThemeToggle />
						</div>
					</div>
					<Toaster />
				</ThemeProvider>
			</body>
		</html>
	)
}
